language: cpp

matrix:
  include:
    - name: "Linux (Clang 10)"
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-8
            - sourceline: 'deb https://apt.llvm.org/xenial/ llvm-toolchain-xenial-10 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-10
            - libstdc++-9-dev
      env:
        - MATRIX_EVAL="CC=clang-10 && CXX=clang++-10"
    - name: "Linux (GCC 9)"
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
      env:
          - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"
    - name: "Windows (MSVC 2017)"
      os: windows
      language: cpp
      env: VS17=true
    - name: "Code Coverage"
      os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
            - lcov
      env:
        - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"
        - CODE_COVERAGE=true

before_install:
    - eval "${MATRIX_EVAL}"
    - if [[ "${CODE_COVERAGE}" == "true" ]]; then gem install coveralls-lcov ; fi

install:
  - |
    if [[ ${TRAVIS_OS_NAME} == "linux" ]]; then
      CMAKE_URL="http://www.cmake.org/files/v3.14/cmake-3.14.0-Linux-x86_64.tar.gz"
      mkdir -p ${TRAVIS_BUILD_DIR}/cmake_3_14
      travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C ${TRAVIS_BUILD_DIR}/cmake_3_14
      export PATH=${TRAVIS_BUILD_DIR}/cmake_3_14/bin:${PATH}
    fi

script:
  - mkdir my_build
  - cd my_build
  - |
    if [[ "${CODE_COVERAGE}" = "true" ]]; then
      cmake -DCMAKE_CXX_FLAGS="-fprofile-arcs -ftest-coverage" -DCMAKE_BUILD_TYPE=Debug ..
      make
      ./../build/Debug_x86_64/UnitTests

      lcov -d . -c -o coverage.info                                      # parse coverage data
      lcov -r coverage.info "/usr*"        -o coverage.info
      lcov -r coverage.info "*/external/*" -o coverage.info
      coveralls-lcov --repo-token=${COVERALLS_REPO_TOKEN} coverage.info  # upload results

      # do not continue with other build configurations after that
      exit
    fi
  - |
    if [[ ${TRAVIS_OS_NAME} == "linux" ]]; then
      cmake ..
      make
    fi
  - |
    if [[ ${TRAVIS_OS_NAME} == "windows" ]]; then
       cmake .. -G "Visual Studio 15 2017 Win64"
       cmake --build .
    fi